# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82c069aa11eec2762785b2aad7f96bb302908e1bd72d8bcc603a30533802f56f50594354dcec8f8fed12205bc8eae86a45b48ce1692ab267da37a975048e7907
  PAYPAL_PERMISSION_URL: "https://sandbox.paypal.com/cgi-bin/webscr?cmd=_grant-permission&request_token="
  TUNNEL_URL: "http://3e73f7fc.ngrok.io"

test:
  secret_key_base: b8d7da94175fa0c309ea237a0f2aba7ced1efb5b5e6c042877410aaade1c4a571bac68ac36cb7887bf905df2011807f92973fb81d3765b2ab576d481a37f4209

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  PAYPAL_PERMISSION_URL: "https://sandbox.paypal.com/cgi-bin/webscr?cmd=_grant-permission&request_token="
